#ifndef ASSETS_H_
#define ASSETS_H_

const int ScreenWidth = 1920;
const int ScreenHeight = 1080;

enum {
	Mesh_Player,
	Mesh_TitlePlayer,
	Mesh_Weapon,
	Mesh_Golem,
	Mesh_StoneSoldier,
	Mesh_Door,
};

enum {
	Title_BGM,
	Select_BGM,
	Play_BGM,
	BossFight_BGM,
	Clear_BGM
};

enum {
	Player_JustAvoid_SE,
	Player_Attack_SE,
	Player_Attack2_SE,
	Enemy_Finish_SE,
	Golem_Attack_SE,
	Golem_Attack2_SE,
	Golem_Attack3_SE,
	Golem_Attack4_SE,
	Golem_Skill_SE,
	Soldier_Attack_SE,
	Soldier_Attack2_SE,
	React_SE,
	PlayerReact_SE,
	PlayerFoot_SE,
	PlayerPowerUp_SE,
	PlayerHeal_SE,
	Click_SE,
	Change_SE,
	Charge_SE
};

enum {
	Octree,
	OctreeCollider
};

enum {
	Texture_Skybox,
};

enum {
	Effect_HealthUpHealBuff,
	Effect_AttackPowerUpBuff,
	Effect_AttackPowerLergeUpBuff,
	Effect_HealSeedBuff,
	Effect_AvoidPerformanceBuff,
	Effect_AvoidDistanceBuff,
	Effect_JustAvoidSlowBuff,
	Effect_DivineProtectionBuff,
	Effect_FullChargeBuff,
	Effect_CrisisChrageBuff,
	Effect_SuperArmorBuff,
	Effect_Attack,
	Effect_Counter,
	Effect_CounterLines,
	Effect_BlowAttack,
	Effect_PushAttack,
	Effect_AvoidAttack,
	Effect_RotatingAttack,
	Effect_InpactAttack,
	Effect_SlamAttack,
	Effect_WildDance,
	Effect_WaveWildDance,
	Effect_Fangs,
	Effect_Arrow
};

enum {
	Option_Text,
	Play_Text,
	Target_Texture,
	Return_Texture,
	X_Button_Texture,
	Clear_Background_Texture,
	Clear_Rank_Texture,
	Clear_SRank_bg,
	Clear_ARank_bg,
	Clear_BRank_bg,
	Clear_CRank_bg,
	Clear_Time_bg,
	Clear_Text,
	Over_Text,
	Load_Texture,
	NowLoad_Texture,
	Num_Texture,
	TextureGaugeRed,
	TextureGaugeGreen,
	Sprite_Title,
	Title_Slayer_Texture,
	Sprite_Equipment,
	Sprite_Battle,
	Text_Texture,
	Text2_Texture,
	Box_Texture,
	AbilityBackFrame_Texture,
	SkillBackFrame_Texture,
	Frame_Texture,
	Select_Frame,
	AbilityFrame_Texture,
	SkillFrame_Texture,
	Equipment_Texture,
	Texture_EffectFlash,
	Texture_Fade,
	Texture_Phase,
	Texture_ItemSelect,
	Texture_Dead,
	BlowAttack_Ability_Explanation_Taxture,
	BlowAttack_Ability_Taxture,
	BlowAttack_Ability_UI_Taxture,
	PushAttack_Ability_Explanation_Taxture,
	PushAttack_Ability_Taxture,
	PushAttack_Ability_UI_Taxture,
	AvoidAttack_Ability_Explanation_Texure,
	AvoidAttack_Ability_Taxture,
	AvoidAttack_Ability_UI_Taxture,
	RotatingAttack_Ability_Explanation_Texure,
	RotatingAttack_Ability_Taxture,
	RotatingAttack_Ability_UI_Taxture,
	InpactGroundAttack_Ability_Explanation_Texure,
	InpactGroundAttack_Ability_Taxture,
	InpactGroundAttack_Ability_UI_Taxture,
	SlamAttack_Ability_Explanation_Texure,
	SlamAttack_Ability_Taxture,
	SlamAttack_Ability_UI_Taxture,
	WildDance_Ability_Explanation_Texure,
	WildDance_Taxture,
	WildDance_UI_Taxture,
	WaveWildDance_Ability_Explanation_Texure,
	WaveWildDance_Ability_Taxture,
	WaveWildDance_Ability_UI_Taxture,
	Fangs_Ability_Explanation_Texure,
	Fangs_Ability_Taxture,
	Fangs_Ability_UI_Taxture,
	HealthUpAndHeal_Skill_Texture,
	HealthUpAndHeal_Skill_UI_Texture,
	HealthUpAndHeal_Skill_Explanation_Texture,
	AttackPowerUp_Skill_Explanation_Texture,
	AttackPowerUp_Skill_Texture,
	AttackPowerUp_Skill_UI_Texture,
	AttackPowerLergeUp_Skill_Explanation_Texture,
	AttackPowerLergeUp_Skill_UI_Texture,
	AttackPowerLergeUp_Skill_Texture,
	HealthHealSeedUp_Skill_Explanation_Texture,
	HealthHealSeedUp_Skill_Texture,
	HealthHealSeedUp_Skill_UI_Texture,
	AvoidPerformanceUp_Skill_Explanation_Texture,
	AvoidPerformanceUp_Skill_Texture,
	AvoidPerformanceUp_Skill_UI_Texture,
	AvoidDistanceUp_Skill_Explanation_Texture,
	AvoidDistanceUp_Skill_Texture,
	AvoidDistanceUp_Skill_UI_Texture,
	JustAvoidSlow_Skill_Explanation_Texture,
	JustAvoidSlow_Skill_Texture,
	JustAvoidSlow_Skill_UI_Texture,
	DivineProtection_Skill_Explanation_Texture,
	DivineProtection_Skill_Texture,
	DivineProtection_Skill_UI_Texture,
	FullCharge_Skill_Explanation_Texture,
	FullCharge_Skill_Texture,
	FullCharge_Skill_UI_Texture,
	CrisisCharge_Skill_Explanation_Texture,
	CrisisCharge_Skill_UI_Texture,
	CrisisCharge_Skill_Texture,
	SuperArmor_Skill_Explanation_Texture,
	SuperArmor_Skill_Texture,
	SuperArmor_Skill_UI_Texture,
	Heal_Portion_Texture,
	Attack_PowerUp_Portion_Texture,
	NumText_Texture,
	IconFrame_Texture,
	NotIcon_Texture,
	NotIconFrame_Texture,
	AttackIcon_Texture,
	AvoidIcon_Texture,
	Text_Texture3,
	Healportion_Explanation_Texture,
};

#endif
